name: cambrio
description: read cool stuff, support good authors, post your stories, get paid.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

# This line goes in the 'podfile'???
#platform: ios, '9.0'

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  shared_preferences: ^2.0.12
  image_picker: ^0.8.4+6
  settings_ui: ^2.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  html_editor_enhanced: ^2.4.0+1
  infinite_scroll_pagination: ^3.1.0
  adaptive_navigation: ^0.0.5
  path_provider: ^2.0.8
  html: ^0.15.0
  share_plus: ^3.0.4
  xml: ^5.3.1
  archive: ^3.2.2
  iridium_reader_widget:
    path: iridium/reader_widget
#  flutter_summernote: ^1.0.0
  flutter_login: ^3.1.0
  firebase_auth: ^3.3.6
  epubx: ^3.0.0
  firestore_search: ^0.1.7
  animate_do: ^2.1.0
  algolia: ^1.0.4
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.8.5
  firebase_storage: ^10.2.9
  firebase_remote_config: ^2.0.2

  # because html coming from html_editor_enhanced includes entity names that xhtml in epub3 does not support
#  html_unescape: ^2.0.0


  # for the book details page
  flutter_html: ^3.0.0-alpha.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4
#  flutter_test:
#    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/white_app_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 500
    - family: Unna
      fonts:
        - asset: assets/fonts/Unna/Unna-Regular.ttf

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/ex_epub/
    - assets/ex_epub/EPUB/
    - assets/ex_epub/META-INF/
    - assets/images/
    - assets/legal/cambrioTermsOfService.html
    - assets/legal/cambrioPrivacyPolicy.html
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
