// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhI623QUVWi68G3ZzXhJqFl8rO4BYGkW4',
    appId: '1:1033037067762:web:db69c2d640391d5199676b',
    messagingSenderId: '1033037067762',
    projectId: 'cambio-46fdc',
    authDomain: 'cambio-46fdc.firebaseapp.com',
    storageBucket: 'cambio-46fdc.appspot.com',
    measurementId: 'G-XRMVRGN68M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRT0nKiYwuk_PWL6gwMQM3D5uGY1_jWv8',
    appId: '1:1033037067762:android:a20c7e56d547bf0799676b',
    messagingSenderId: '1033037067762',
    projectId: 'cambio-46fdc',
    storageBucket: 'cambio-46fdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bWFE8rBaXl-QwmNbxXbB9BL4hoQP55Q',
    appId: '1:1033037067762:ios:83b0d6a9077a369a99676b',
    messagingSenderId: '1033037067762',
    projectId: 'cambio-46fdc',
    storageBucket: 'cambio-46fdc.appspot.com',
    androidClientId: '1033037067762-i26f4m78au0cef0d7dd1f5bbd7mln1ih.apps.googleusercontent.com',
    iosClientId: '1033037067762-gdef8ad82dpvu3toegeg6b8t0vhngpgf.apps.googleusercontent.com',
    iosBundleId: 'app.cambrio',
  );
}
